# Generated by Django 4.2.5 on 2025-01-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyValueData',
        ),
    ]
