# Generated by Django 4.2.5 on 2025-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_keyvaluedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('multiple_int_values', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
