# Generated by Django 4.2.5 on 2025-05-09 04:02

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_keyvaluedata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('selected_options_from_one_to_five', models.TextField(blank=True, null=True)),
                ('selected_options_rest_questions', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
            },
        ),
        migrations.AlterField(
            model_name='keyvaluedata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.unique_image_filename),
        ),
    ]
