# Generated by Django 4.2.5 on 2025-05-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_surveyresponse_alter_keyvaluedata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='correctly_answered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
