# Generated by Django 4.2.5 on 2025-05-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_surveyresponse_correctly_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
