# Generated by Django 4.2.5 on 2025-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_surveyresponse_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
